"""
Crawler'lar için metin kalıpları ve filtreler
"""

# Hepsiburada için metin kalıpları
HEPSIBURADA_PATTERNS = {
    # Ürün özelliklerinde aranacak metinler (öncelik sırasına göre)
    'wanted_texts': [
        "Akü Sayısı",
        "Testere Bıçağı Çapı",
        "Maksimum Tork",
        "Tork Ayarı",
        "Türü",
        "Volt",
        "Akü",
        "Amper",
        "Ahşap Delme Çapı",
        "Çelik Delme Çapı",
        "Delme Derinliği",
        "Delme Çapı",
        "Güç (W)",
        "Darbe Gücü (Joule)",
        "Boşta Maksimum Devir Sayısı (Devir/dk)",
        "Ağırlık",
        "Maksimum Darbe Sayısı (Darbe/dk)",
        "Metal Delme Çapı",
        "Beton Delme Çapı",
        "Akü Bilgisi",
        "Çalışma Şekli",
        "Çalışma Süresi",
        "Çalışma Sıcaklığı",
        "Çalışma Basıncı",
        "Çalışma Hızı",
        "Renk",
        "Uygulama Yüzeyi",
        "Toz Emme",
        "Hız Ayarı",
        "Çanta",
        "Taşıma Kapasitesi",
        "Katlanabilir",
        "Malzeme",
        "Teker Tipi",
        "Disk Çapı",
        "Devir Ayarı",
        "Watt Değeri",
        "Devir",
        "Aksesuar Seti",
        "Aksesuar",
        "Ahşap Kesme (mm)",
        "Metal Kesme (mm)",
        "Türü",
        "Kaldıraç",
        "Kaldırma Kapasitesi",
        "Elektrot Çapı",
        "Çapı",
        "Maksimum Güç (kVA)",
        "Minimum Akım Değeri",
        "Ağırlık (kg)",
        "Ürün Çeşiti",
        "Güvenlik Standardı",
        "Malzeme",
        "Dış Taban",
        "WRU",
        "Su Geçirmez",
        "Koruma Sınıfı",
        "Materyal",
        "EN Standartı",
        "Astar malzemesi",
        "Kaplama malzemesi",
        "Mandren Tipi",
        "Mandren Ölçüsü (mm)",
        "Mandren Çapı (mm)",
        "Mandren Uzunluğu (mm)",
        "Miktar"
    ],

    # Açıklamadan temizlenecek istenmeyen metinler
    'unwanted_texts': [
        "Garanti Süresi (Ay)",
        "Yurt Dışı Satış",
        "Stok Kodu",
        "Stok Adedi",
        "Seçenek",
        "Diğer",
        "Kombin ID",
        "Hatalı içerik bildir",
        "Taksit",
        "Stok",
        "Kargo",
        "Teslimat",
        "İade",
        "Satıcı",
        "Mağaza",
        "Kampanya",
        "Hediye",
        "Puan"
    ],

    # Açıklamadan temizlenecek istenmeyen ifadeler
    'unwanted_phrases': [
        "Satın aldığınız ürünün orijinal olduğunu gösteren",
        "Satın aldığınız ürünün orijinal olduğunu",
        "Satın aldığınız ürünün",
        "Ürünün orijinal olduğunu gösteren",
        "Ürünün orijinal olduğunu",
        "Ürün özellikleri",
        "Ürünün",
        "Ürünlerimiz",
        "Ürünümüz",
        "Ürünler",
        "Ürün",
        "Fiyat",
        "Fiyatı",
        "Fiyatlar",
        "Kampanya",
        "Kampanyalı",
        "İndirim",
        "İndirimli",
        "Stok",
        "Stokta",
        "Stoklarımızda",
        "Kargo",
        "Kargoya",
        "Kargoyla",
        "Teslimat",
        "Teslim",
        "Taksit",
        "Taksitli",
        "Garanti",
        "Garantili",
        "Orijinal",
        "Orjinal",
        "Mağaza",
        "Mağazamız",
        "Satıcı",
        "Satış",
        "Satışta",
        "Hediye",
        "Hediyeli",
        "Puan",
        "Puanlı",
        "Hatalı içerik bildir"
    ]
}

# Diğer siteler için benzer pattern'lar eklenebilir
# TRENDYOL_PATTERNS = { ... }
# N11_PATTERNS = { ... } 